services:
  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - ${POSTGRES_PORT}:5432

  frontend:
    env_file:
      - .env.dev
    environment:
      NODE_ENV: "dev"
    ports:
      - ${FRONTEND_PORT}:3000

  backend:
    env_file:
      - .env.dev
    environment:
      NODE_ENV: "dev"
    ports:
      - ${BACKEND_PORT}:1337

  hasura:
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "APP-SECRET-DEVELOPMENT-LOCALHOST"
      APP_SECRET: "APP-SECRET-DEVELOPMENT-LOCALHOST"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # in dev we want to start our console so migrations get created locally
      HASURA_GRAPHQL_AUTH_HOOK: "http://host.docker.internal:3000/api/hasura"
      NUXT_PUBLIC_BACKEND_URL: "http://host.docker.internal:1337"
    ports:
      - "8080:8080"

  bull-monitor:
    ports:
      - "4000:3000"

  # This is our development smtp server. On prod we use one installed on linux
  mailhog:
    image: mailhog/mailhog
    ports:
      - "587:1025"
      - "8025:8025"
