table:
  name: user_provider
  schema: public
object_relationships:
  - name: provider
    using:
      foreign_key_constraint_on: provider_id
  - name: user
    using:
      foreign_key_constraint_on: id
