table:
  name: notification
  schema: public
object_relationships:
  - name: event
    using:
      foreign_key_constraint_on: event_id
  - name: user
    using:
      foreign_key_constraint_on: user_id
select_permissions:
  - role: manager
    permission:
      columns:
        - id
        - payload
        - created_at
        - event_id
        - user_id
      filter: {}
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - id
        - payload
        - created_at
        - event_id
        - user_id
      filter: {}
      allow_aggregations: true
